Repository kalviumcommunity/S76_Rahulrr_Capstone_Pollx, pull requests merged in 2025-05, with the labels that each got.

#11 implement relation between entities
  server/controllers/poll.js
  server/controllers/user.js
  server/docs.bruno/create-user.bru
  server/docs.bruno/users-polls.bru
  server/models/Poll.js
  server/server.js
Labels: Review effort 2/5

#14 create components
  client/README.md
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.jsx
  client/src/components/Button.jsx
  client/src/components/CTASection.jsx
  client/src/components/CategoriesSection.jsx
  client/src/components/FeaturesSection.jsx
  client/src/components/Footer.jsx
  client/src/components/HeroSection.jsx
  client/src/components/HowItWorksSection.jsx
  client/src/components/Navbar.jsx
  client/src/components/PollCard.jsx
  client/src/components/SectionHeader.jsx
  client/src/components/TestimonialsSection.jsx
  client/src/index.css
  client/src/pages/LandingPage.jsx
  client/vite.config.js
Labels: Review effort 3/5

#15 Auth
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/api/auth.js
  client/src/components/CTASection.jsx
  client/src/components/HeroSection.jsx
  client/src/components/LoginForm.jsx
  client/src/components/Navbar.jsx
  client/src/components/SignupForm.jsx
  client/src/pages/Dashboard.jsx
  client/src/pages/LoginPage.jsx
  client/src/pages/SignupPage.jsx
  package-lock.json
  package.json
  server/config/db.js
  server/controllers/auth.js
  server/controllers/user.js
  server/docs.bruno/signup.bru
  server/models/User.js
  server/package-lock.json
  server/package.json
  server/routes/routes.js
  server/server.js
Labels: Review effort 3/5

#16 Done Signup/Login
  client/src/components/LoginForm.jsx
  client/src/components/SignupForm.jsx
Labels: Review effort 2/5

#17 Add Google OAuth authentication with environment variables for creden…
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/api/auth.js
  client/src/components/GoogleLoginButton.jsx
  client/src/components/LoginForm.jsx
  client/src/components/ProtectedRoute.jsx
  client/src/components/SignupForm.jsx
  client/src/pages/AuthSuccessPage.jsx
  client/src/pages/Dashboard.jsx
  client/src/pages/LoginPage.jsx
  server/config/passport.js
  server/controllers/auth.js
  server/models/User.js
  server/package-lock.json
  server/package.json
  server/routes/routes.js
  server/server.js
Labels: Review effort 4/5

#18 Add JW tokens for authentication
  server/config/db.js
  server/server.js
Labels: Review effort 3/5
